activityTime	=0			--Controller for when Activities are running
birdegg			=0			--Players Bird Egg count
chopTime		=0			--How much time is left to chop
currentTime		=0			--Stores the app's current time (REMOVE)
didLevel		=1			--Detects whether player has levelled up or not
DisplayedExp	=0			--How much experience is required to reach the next level
experience		=0			--Players current Experience
expNeeded		=0			--How much Experience the player need to level up
firstTimeLoad	=1			--Checks whether the game has been launched for the first time
fish			=0			--Players Fish count
fishTime		=0			--How much time is left to fish
forageTime		=0			--How much time is left to forage
healedHP		=0			--How much the player healed up (DUNGEON, TAVERN) [REMOVE]
inFight			=0			--Checks if the player is currently in a fight
inspirePotions	=0			--Potions of Inspiration. Grants player a massive XP gain.
m_con			=10			--Monsters Constitution
m_conMod		=0			--Monsters Constitution Modifier
m_def			=10			--Monsters defense
m_hp			=10			--Monsters current health
m_level			=1			--Monsters level
m_maxhp			=10			--Monsters max health
m_str			=10			--Monsters Strength
m_strMod		=0			--Monsters Strength Modifier
metal			=0			--Players Metal count
mineTime		=0			--How much time is left to mine
monster			=''			--Monster Name
monsterBaseExp	=10			--Base Experience for all monsters Killed
monstersKilled	=0			--Players monster kill count
p_cha			=12			--Players Charisma
p_chaMod		=1			--Players Charisma Modifier
p_con			=12			--Players Constitution
p_conMod		=1			--Players Constitution Modifier
p_def			=14			--Players defense
p_hp			=50			--Players current health
p_level			=1			--Players current level
p_maxhp			=50			--Players max health
p_str			=12			--Players Strength
p_strMod		=1			--Players Strength Modifier
p_sur			=12			--Players Survival
p_surMod		=1			--Players Survival Modifier
pastTime		=0			--Stores app's closed time
playerName		=''			--Player's username
potions			=5			--Players current Potions
rainbowtrout	=0			--Players Rainbow Trout count
revivalStone	=1			--Players current Revival Stones
scrap			=0			--Players Scrap count
silvercoin		=0			--Players Silver Coin count
stone			=0			--Players Stone count
welcomeEnabled	=0			--Checks to see if the Welcome message setting is enabled
welcomePopup	=''			--Welcome message text (REMOVE)
wood			=0			--Players Wood count
zoulds			=0			--Players current Zoulds

-- Monster Lists  (Name, 				Health, 	Strength, Defense, Exp)
kobold = 		{"Kobold", 			5, 		7, 		12, 	3}
goblin = 		{"Goblin", 			7, 		8, 		15, 	4}
pseudoDragon =	{"Pseudodragon", 	7, 		6, 		13, 	5}
imp = 			{"Imp", 			10, 	6, 		13,		6}
wolf = 			{"Wolf", 			11, 	12, 	13, 	7}
skeleton = 		{"Skeleton", 		13, 	10, 	13, 	8}
fairy = 		{"Fairy", 			15, 	4, 		15, 	2}
ooze = 			{"Ooze", 			22, 	12, 	8, 		10}
ghoul = 		{"Ghoul", 			22, 	13, 	12, 	12}
satyr = 		{"Satyr", 			31, 	12, 	14, 	13}
hellhound = 	{"HellHound", 		45, 	17, 	15, 	14}
werewolf = 		{"Werewolf", 		58, 	15, 	11, 	16}
mimic =			{"Mimic",			58, 	17, 	12, 	17}
undeadKnight = 	{"Undead Knight", 	60, 	14, 	18, 	25}
windWraith = 	{"Wind Wraith", 	67, 	6, 		13, 	22}
wanyuudoo = 	{"Wanyuudoo", 		68, 	14, 	13, 	23}
kappa = 		{"Kappa", 			76, 	19, 	16, 	24}
couatl = 		{"Couatl", 			97, 	16, 	19, 	29}
chimera = 		{"Chimera", 		114, 	19, 	14, 	32}
lich = 			{"Lich", 			135, 	11, 	17, 	45}
yukiOnna = 		{"Yuki-Onna", 		143, 	12, 	16, 	49}